name: Deploy to WebLogic

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List Files
        run: ls -l

      - name: Deploy WAR to WebLogic container
        run: |
          docker cp sample.war 3e774581615b:/u01/oracle/user_projects/domains/base_domain/autodeploy/
